# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/info/I-2/DSD/washingmachine/washingmachine.cache/wt [current_project]
set_property parent.project_path E:/info/I-2/DSD/washingmachine/washingmachine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/info/I-2/DSD/washingmachine/washingmachine.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/RobertComp.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/asyncrom.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/bindec.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/binencoder.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/radiator.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/romandenc.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/romsource.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/tandshield.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/tflipflop.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/tshield.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/twobincount.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/twobitcountthree.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/washregister.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/seconds.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/minutes.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/mux2to1.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/countdown5to1.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/countdown9to0.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/washcyclereg.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/mihneacomp.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/freq100mhzto2hz.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/freq100mhzto14hz.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/freq100mhzto17hz.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/freq100mhzto20hz.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/heatrom.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/cyclocount.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/timerom.vhd
  E:/info/I-2/DSD/washingmachine/washingmachine.srcs/sources_1/new/mux8to1.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/info/I-2/DSD/washingmachine/washingmachine.srcs/constrs_1/new/constrom.xdc
set_property used_in_implementation false [get_files E:/info/I-2/DSD/washingmachine/washingmachine.srcs/constrs_1/new/constrom.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RobertComp -part xc7a35tcpg236-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RobertComp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RobertComp_utilization_synth.rpt -pb RobertComp_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
